substitutions:
  doorbell_user: !secret doorbell_user
  doorbell_password: !secret doorbell_password

esphome:
  name: t-display-s3-pro
  friendly_name: T-Display S3 Pro

psram:
  mode: octal

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

logger:
api:
ota:
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

output:
  - platform: ledc
    pin: GPIO48
    id: backlight_output
    frequency: 9765Hz

light:
  - platform: monochromatic
    output: backlight_output
    name: "T-Display Backlight"
    restore_mode: ALWAYS_ON

spi:
  - id: spi_bus
    clk_pin: 18
    mosi_pin: 17

display:
  - platform: mipi_spi
    model: t-display-s3-pro
    spi_id: spi_bus
    rotation: 90
    id: my_display

interval:
  - interval: 5s
    then:
      - http_request.get:
          url: "http://192.168.50.128/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=esphome&user=${doorbell_user}&password=${doorbell_password}&snapType=sub&width=320&height=170"
          verify_ssl: false
          on_response:
            - if:
                condition:
                  lambda: 'return body.size() > 0;'
                then:
                  - display.image:
                      id: my_display
                      x: 0
                      y: 0
                      data: !lambda 'return body;'
                      width: 320
                      height: 170
                else:
                  - display.printf:
                      id: my_display
                      x: 10
                      y: 10
                      format: "Failed to fetch image"
